name: 'Unit Tests'
description: 'Run Ansible unit tests for variable validation, templates, and workflow logic'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13.6'

runs:
  using: 'composite'
  steps:
    - name: Setup Ansible Environment
      uses: ./.github/actions/setup-ansible
      with:
        python-version: ${{ inputs.python-version }}
        cache-key-suffix: 'unit-tests'

    - name: Run variable validation tests
      shell: bash
      run: |
        ansible-playbook tests/unit-tests/variable-validation.yml

    - name: Run template rendering tests
      shell: bash
      run: |
        ansible-playbook tests/unit-tests/template-rendering.yml

    - name: Run workflow logic tests
      shell: bash
      run: |
        ansible-playbook tests/unit-tests/workflow-logic.yml

    - name: Run error handling tests
      shell: bash
      run: |
        ansible-playbook tests/unit-tests/error-handling.yml

    - name: Run mock authentication validation tests
      shell: bash
      run: |
        ansible-playbook tests/unit-tests/mock-authentication-validation.yml