# Pre-commit hooks for Network Device Upgrade System
# Install: pip install pre-commit && pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Repository hygiene
  - repo: local
    hooks:
      - id: no-backup-files
        name: Check for backup files
        entry: '\.(bak|tmp|old)$'
        language: pygrep
        files: '.*'
        description: Prevent committing backup files (.bak, .tmp, .old)

  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Trim trailing whitespace
      - id: end-of-file-fixer
        name: Fix end of files
      - id: check-yaml
        name: Check YAML syntax
        args: ['--unsafe']  # Allow custom YAML tags used by Ansible
      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-case-conflict
        name: Check for case conflicts
      - id: mixed-line-ending
        name: Fix mixed line endings

  # Ansible linting
  - repo: https://github.com/ansible/ansible-lint
    rev: v24.2.0
    hooks:
      - id: ansible-lint
        name: Ansible Lint
        files: \.(yaml|yml)$
        args:
          - --profile=production
          - --exclude=.github/
          - --exclude=tests/

  # YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        name: YAML Lint
        args:
          - --strict
          - --config-file=.yamllint.yml

  # Python linting (for scripts)
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
        name: Format Python with Black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        name: Lint Python with Flake8
        args: ['--max-line-length=120', '--extend-ignore=E203,W503']

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        name: ShellCheck
        args: ['-x']  # Follow source statements

  # Security checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        name: Detect secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: |
          (?x)^(
            tests/.*|
            .*/test-.*|
            .*\.example\..*
          )$

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        name: Lint Markdown
        args: ['--fix']

# Configuration
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: weekly
  skip: []
  submodules: false
