name: 'Setup Ansible Environment'
description: 'Reusable action to set up Python, Ansible, and collections'
inputs:
  python-version:
    description: 'Python version to install'
    required: false
    default: '3.14.0'
  install-molecule:
    description: 'Whether to install molecule testing framework'
    required: false
    default: 'false'
  cache-key-suffix:
    description: 'Suffix for cache key to allow different caches per job'
    required: false
    default: 'default'

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Cache uv dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ inputs.cache-key-suffix }}-${{ inputs.install-molecule }}-${{ hashFiles('**/requirements*.txt', 'ansible-content/collections/requirements.yml') }}
        restore-keys: |
          ${{ runner.os }}-uv-${{ inputs.cache-key-suffix }}-${{ inputs.install-molecule }}-
          ${{ runner.os }}-uv-${{ inputs.cache-key-suffix }}-
          ${{ runner.os }}-uv-

    - name: Install uv package manager
      shell: bash
      run: |
        python -m pip install --upgrade uv

    - name: Install Ansible and basic dependencies
      shell: bash
      run: |
        uv pip install --system --upgrade ansible yamllint ansible-lint

    - name: Install molecule (if requested)
      if: inputs.install-molecule == 'true'
      shell: bash
      run: |
        uv pip install --system molecule molecule-plugins[docker] docker

    - name: Cache Ansible collections
      uses: actions/cache@v4
      with:
        path: ~/.ansible/collections
        key: ${{ runner.os }}-ansible-collections-${{ hashFiles('ansible-content/collections/requirements.yml') }}
        restore-keys: |
          ${{ runner.os }}-ansible-collections-

    - name: Install Ansible collections
      shell: bash
      run: |
        # Only install if not cached or if requirements changed
        if [ ! -d ~/.ansible/collections ] || [ ! -f ~/.ansible/collections/.installed ]; then
          ansible-galaxy collection install \
            -r ansible-content/collections/requirements.yml \
            --force
          touch ~/.ansible/collections/.installed
        else
          echo "Ansible collections found in cache"
        fi