---
# Ansible Collections Requirements for Network Device Upgrade System
# Latest available versions as of October 30, 2025

collections:
  # Cisco Network Collections
  - name: cisco.nxos
    version: "11.0.0"
    source: https://galaxy.ansible.com
  - name: cisco.ios
    version: "11.1.1"
    source: https://galaxy.ansible.com

  # Fortinet Collection
  - name: fortinet.fortios
    version: "2.4.0"
    source: https://galaxy.ansible.com

  # Core Network Collections
  - name: ansible.netcommon
    version: "8.1.0"
    source: https://galaxy.ansible.com

  # Utility Collections
  - name: community.general
    version: "11.4.0"
    source: https://galaxy.ansible.com
  - name: ansible.posix
    version: "1.6.2"
    source: https://galaxy.ansible.com

  # Crypto and Security
  - name: community.crypto
    version: "3.0.5"
    source: https://galaxy.ansible.com

  # HTTP and API Collections
  - name: ansible.utils
    version: "6.0.0"
    source: https://galaxy.ansible.com

  # NetBox Integration
  - name: netbox.netbox
    version: "3.21.0"
    source: https://galaxy.ansible.com

# Installation command:
# ansible-galaxy collection install -r collections/requirements.yml --force

# Note: All versions are latest available releases verified on Oct 30, 2025
# Compatible with Ansible 11.0.0 (ansible-core 2.18.10) and Python 3.13.9
