---
# Ansible Collections Requirements for Network Device Upgrade System
# Production-ready collections with specific version requirements

collections:
  # Cisco Network Collections
  - name: cisco.nxos
    version: ">=5.3.0"
    source: https://galaxy.ansible.com
  - name: cisco.ios
    version: ">=6.0.0"
    source: https://galaxy.ansible.com

  # Fortinet Collection  
  - name: fortinet.fortios
    version: ">=2.3.0"
    source: https://galaxy.ansible.com

  # Core Network Collections
  - name: ansible.netcommon
    version: ">=6.1.0"
    source: https://galaxy.ansible.com
  - name: community.network
    version: ">=5.0.0"
    source: https://galaxy.ansible.com

  # Utility Collections
  - name: community.general
    version: ">=8.0.0" 
    source: https://galaxy.ansible.com
  - name: ansible.posix
    version: ">=1.5.0"
    source: https://galaxy.ansible.com

  # Crypto and Security
  - name: community.crypto
    version: ">=2.15.0"
    source: https://galaxy.ansible.com

  # HTTP and API Collections
  - name: ansible.utils
    version: ">=3.1.0"
    source: https://galaxy.ansible.com

  # NetBox Integration
  - name: netbox.netbox
    version: ">=3.18.0"
    source: https://galaxy.ansible.com

# Installation command:
# ansible-galaxy collection install -r collections/requirements.yml --force