---
# Metamako MOS Specific Configuration
# For ultra-low latency switches

# Connection settings
ansible_network_os: ansible.netcommon.network_cli
ansible_connection: ansible.netcommon.network_cli
ansible_user: "{{ vault_metamako_username | default('admin') }}"
ansible_password: "{{ vault_metamako_password }}"
ansible_ssh_common_args: >
  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null

# Platform specific settings
platform_type: "metamako_mos"
vendor: "metamako"
device_family: "metamux"

# Ultra-low latency requirements
max_allowed_latency_ns: 100
latency_degradation_threshold: 1.1  # 10% max increase
enable_latency_monitoring: true

# Specialized component validation
check_metawatch: true
check_metamux: true
validate_latency_performance: true

# Image management - Server-initiated PUSH only
# All images are pushed from the upgrade server to devices via SCP/SFTP
image_verification_required: true

# Performance settings
performance_mode: "low_latency"
enable_performance_benchmarks: true
benchmark_timeout: 300

# Network settings
management_vlan: 1
management_gateway: "192.168.1.1"
ntp_servers:
  - "pool.ntp.org"
  - "time.nist.gov"

# Timing validation (critical for trading environments)
validate_pps_sync: true  # Pulse Per Second synchronization
validate_time_accuracy: true
max_time_drift_ms: 1

# Interface validation specific to Metamako
validate_fiber_optics: true
check_signal_integrity: true
validate_port_mapping: true

# Environmental monitoring
monitor_temperature: true
temperature_alert_threshold: 40  # Celsius
monitor_power_consumption: true

# Failover and redundancy
validate_redundant_paths: true
check_link_aggregation: false  # May not be applicable

# Upgrade settings specific to MOS
mos_upgrade_method: "staged"
verify_staged_image: true
staging_timeout: 1800

# Latency measurement settings
latency_measurement_interval: 10  # seconds
latency_sample_count: 100
continuous_monitoring: true

# Validation thresholds
max_packet_loss_percent: 0.01
max_jitter_ns: 50
min_throughput_gbps: 10

# Recovery settings
auto_recovery_enabled: true
recovery_timeout: 300
rollback_on_latency_degradation: true

# Specialized features
enable_metawatch_logging: true
metamux_config_validation: true
port_mirroring_validation: false

# Time synchronization (critical)
ptp_enabled: true  # Precision Time Protocol
ptp_domain: 0
validate_ptp_sync: true

# Hardware validation
validate_fpga_status: true
check_ddr_memory: true
validate_pcie_links: true

# Application management
manage_applications: false  # Enable application management during upgrades
application_action: ""  # install, remove, enable, disable
application_name: ""
application_source: ""  # URL or local path to application file
application_filename: >
  # Optional: specify filename on device (defaults to basename of source)
applications_to_enable: []
applications_to_disable: []
applications_to_force_shutdown: []

# EOS extension management
eos_extension_action: ""  # install, remove
eos_extension_name: ""
eos_extension_source: ""  # URL or local path to EOS extension file
eos_extension_filename: >
  # Optional: specify filename on device (defaults to basename of source)
