---
# Metamako MOS Test Environment Preparation
# Sets up HFT-specific test environment and mocks
- name: Prepare - Setup Metamako Test Environment
  hosts: all
  gather_facts: false
  tasks:
    - name: Install system dependencies for testing
      ansible.builtin.package:
        name:
          - python3-pip
          - curl
          - netcat-openbsd
        state: present
      become: true
      failed_when: false  # May not be available in container

    - name: Create mock network command wrapper
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          # Mock CLI command wrapper for Metamako testing
          case "$1" in
            "show version")
              cat << EOF
          Model: MetaConnect-48
          Version: 2.0.8
          Serial: MK2345HFT001
          Build: 2023-08-15T10:30:00Z
          Features: HFT, PTP, MetaWatch, MetaMux
          Temperature: 45.2°C
          Optics Temperature: 52.1°C
          PTP Status: Synchronized
          Timing Reference: GPS+PTP
          EOF
              ;;
            "show metawatch status")
              echo "MetaWatch: Enabled, Running, Latency Monitor Active"
              ;;
            "show metamux status")
              echo "MetaMux: Enabled, 4 active sessions, Load balancing active"
              ;;
            "show interfaces brief")
              echo "Interface Status: 48 ports active, all optical links up"
              ;;
            "show system temperature")
              echo "System: 45.2°C, Optics: 52.1°C, All sensors normal"
              ;;
            "show timing status")
              echo "PTP: Synchronized, GPS: Locked"
              echo "Jitter: 12ns, Accuracy: ±1μs"
              ;;
            *)
              echo "Command output: $1"
              ;;
          esac
        dest: /usr/local/bin/mock-cli
        mode: '0755'
      become: true
      failed_when: false

    - name: Create mock file system structure for testing
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - /tmp/test-metamako
        - /var/backup/metamako
        - /boot/firmware
        - /opt/metawatch/bin
        - /opt/metamux/bin
        - /var/log/metamako
        - /etc/metamako

    - name: Create mock configuration files
      ansible.builtin.copy:
        content: "{{ item.content }}"
        dest: "{{ item.path }}"
        mode: "{{ item.mode }}"
      loop:
        - path: /etc/metamako/device.conf
          mode: '0644'
          content: |
            device_type=MetaConnect-48
            serial=MK2345HFT001
            hft_mode=enabled
            latency_target=500ns

        - path: /opt/metawatch/bin/metawatch
          mode: '0755'
          content: |
            #!/bin/bash
            echo "MetaWatch v2.0.8 - Latency monitoring active"

        - path: /opt/metamux/bin/metamux
          mode: '0755'
          content: |
            #!/bin/bash
            echo "MetaMux v2.0.8 - Load balancing active"

    - name: Create mock firmware files
      ansible.builtin.copy:
        content: |
          # Mock Metamako firmware image v2.1.3
          # Contains: kernel, applications, configuration
          # Size: 128MB (mocked)
          # Checksum: sha256:abcd1234...
        dest: "{{ item }}"
        mode: '0644'
      loop:
        - /tmp/metamakoos-2.0.8.tar.gz
        - /tmp/metamakoos-2.1.3.tar.gz
        - /boot/firmware/current.tar.gz

    - name: Create mock timing reference files
      ansible.builtin.copy:
        content: |
          PTP_STATUS=synchronized
          GPS_STATUS=locked
          TIMING_ACCURACY=1
          JITTER_NS=12
          REFERENCE_CLOCK=external_10mhz
        dest: /etc/metamako/timing.status
        mode: '0644'

    - name: Setup environment variables for testing
      ansible.builtin.set_fact:
        ansible_python_interpreter: /usr/bin/python3
        metamako_test_mode: true
        mock_cli_available: true

    - name: Validate test environment setup
      ansible.builtin.debug:
        msg: |
          Metamako Test Environment Prepared:
          - Mock CLI commands: ✅
          - File system structure: ✅
          - Configuration files: ✅
          - Firmware images: ✅
          - Timing references: ✅

          Ready for HFT upgrade testing
