---
# Post-Upgrade Service Validation for Metamako MOS
# Validates that Metawatch, Metamux, and telemetry services return to pre-upgrade state

- name: Post-upgrade Metawatch service check
  ansible.netcommon.cli_command:
    command: show metawatch running
  changed_when: false
  register: post_metawatch_running
  failed_when: false
  when: metamako_upgrade_state.metawatch_enabled | default(false)
- name: Post-upgrade Metamux service check
  ansible.netcommon.cli_command:
    command: show metamux running
  changed_when: false
  register: post_metamux_running
  failed_when: false
  when: metamako_upgrade_state.metamux_enabled | default(false)
- name: Post-upgrade telemetry service check
  ansible.netcommon.cli_command:
    command: show telemetry running
  changed_when: false
  register: post_telemetry_running
  failed_when: false
  when: metamako_upgrade_state.telemetry_enabled | default(false)
- name: Parse post-upgrade service status
  ansible.builtin.set_fact:
    post_upgrade_services:
      metawatch_running: '{{ post_metawatch_running.rc == 0 and ''running'' in post_metawatch_running.stdout
        | lower }}'
      metamux_running: '{{ post_metamux_running.rc == 0 and ''running'' in post_metamux_running.stdout
        | lower }}'
      telemetry_running: '{{ post_telemetry_running.rc == 0 and ''running'' in post_telemetry_running.stdout
        | lower }}'
- name: Validate Metawatch service recovery
  ansible.builtin.assert:
    that:
    - post_upgrade_services.metawatch_running == pre_upgrade_baseline.metawatch_running
    fail_msg: 'Metawatch service status changed after upgrade - was {{ pre_upgrade_baseline.metawatch_running
      }} , now {{ post_upgrade_services.metawatch_running }} '
    success_msg: ✓ Metawatch service status maintained after upgrade
  when: metamako_upgrade_state.metawatch_enabled | default(false)
- name: Validate Metamux service recovery
  ansible.builtin.assert:
    that:
    - post_upgrade_services.metamux_running == pre_upgrade_baseline.metamux_running
    fail_msg: Metamux service status changed after upgrade - was {{ pre_upgrade_baseline.metamux_running
      }}, now {{ post_upgrade_services.metamux_running }}
    success_msg: ✓ Metamux service status maintained after upgrade
  when: metamako_upgrade_state.metamux_enabled | default(false)
- name: Validate telemetry service recovery
  ansible.builtin.assert:
    that:
    - post_upgrade_services.telemetry_running == pre_upgrade_baseline.telemetry_running
    fail_msg: 'Telemetry service status changed after upgrade - was {{ pre_upgrade_baseline.telemetry_running
      }} , now {{ post_upgrade_services.telemetry_running }} '
    success_msg: ✓ Telemetry service status maintained after upgrade
  when: metamako_upgrade_state.telemetry_enabled | default(false)
- name: Restart Metawatch if it should be running
  ansible.netcommon.cli_command:
    ansible.builtin.command: metawatch start
  when:
  - metamako_upgrade_state.metawatch_enabled | default(false)
  - pre_upgrade_baseline.metawatch_running | default(false)
  - not post_upgrade_services.metawatch_running | default(false)
- name: Restart Metamux if it should be running
  ansible.netcommon.cli_command:
    ansible.builtin.command: metamux start
  when:
  - metamako_upgrade_state.metamux_enabled | default(false)
  - pre_upgrade_baseline.metamux_running | default(false)
  - not post_upgrade_services.metamux_running | default(false)
- name: Restart telemetry if it should be running
  ansible.netcommon.cli_command:
    ansible.builtin.command: telemetry start
  when:
  - metamako_upgrade_state.telemetry_enabled | default(false)
  - pre_upgrade_baseline.telemetry_running | default(false)
  - not post_upgrade_services.telemetry_running | default(false)
- name: Final service status report
  ansible.builtin.debug:
    msg: "Post-Upgrade Service Status Summary:\nMetawatch: \n  {{ 'Running' if post_upgrade_services.metawatch_running\
      \ else 'Stopped' }}\n   (Expected: \n  {{ 'Running' if pre_upgrade_baseline.metawatch_running\
      \ else 'Stopped' }}\n  )\nMetamux: \n  {{ 'Running' if post_upgrade_services.metamux_running\
      \ else 'Stopped' }}\n   (Expected: \n  {{ 'Running' if pre_upgrade_baseline.metamux_running\
      \ else 'Stopped' }}\n  )\nTelemetry: \n  {{ 'Running' if post_upgrade_services.telemetry_running\
      \ else 'Stopped' }}\n   (Expected: \n  {{ 'Running' if pre_upgrade_baseline.telemetry_running\
      \ else 'Stopped' }}\n  )\nStatus: \n  {{ 'ALL SERVICES RECOVERED' if (post_upgrade_services.metawatch_running\
      \ == pre_upgrade_baseline.metawatch_running and post_upgrade_services.metamux_running\
      \ == pre_upgrade_baseline.metamux_running and post_upgrade_services.telemetry_running\
      \ == pre_upgrade_baseline.telemetry_running) else 'SERVICE RECOVERY ISSUES'\
      \ }}"
