---
# Network Device Upgrade System - Inventory Configuration
#
# This file defines devices for firmware upgrades across multiple vendor platforms.
#
# Documentation: See docs/inventory-parameters.md for complete parameter reference
#
# Structure:
#   - Define hosts under platform-specific groups (cisco_nxos, cisco_iosxe, fortios, opengear, metamako_mos)
#   - All group-level parameters are defined in group_vars/<platform>.yml
#   - Host-specific overrides can be defined inline or in host_vars/<hostname>.yml
#
# Quick Start:
#   1. Add your device under the appropriate platform group
#   2. Set required parameters: ansible_host, platform
#   3. Override platform defaults as needed (optional)
#   4. Refer to group_vars/all.yml for global parameters
#   5. Refer to group_vars/<platform>.yml for platform-specific parameters

all:
  children:
    # ============================================================================
    # CISCO NX-OS DEVICES (Nexus Switches)
    # ============================================================================
    cisco_nxos:
      hosts:
        # Example NX-OS device with minimal configuration
        nxos-switch-01:
          ansible_host: 192.168.1.10
          platform: nxos

        # Example NX-OS device with common overrides
        nxos-switch-02:
          ansible_host: 192.168.1.11
          platform: nxos
          # Override target firmware version for this specific host
          target_firmware_version: "10.4.5.M"
          # Override authentication (if different from group_vars)
          ansible_user: "{{ vault_nxos_switch02_username }}"
          ansible_password: "{{ vault_nxos_switch02_password }}"
          # Device identification
          site_name: "datacenter-east"
          device_role: "core-switch"

        # Example NX-OS device with advanced settings
        nxos-switch-03:
          ansible_host: 192.168.1.12
          platform: nxos
          # ISSU settings
          enable_issu: true
          issu_timeout: 3600
          # EPLD upgrade settings
          enable_epld_upgrade: true
          target_epld_version: "10.4.5"
          allow_disruptive_epld: false
          # Storage management
          min_free_space_mb: 3000
          cleanup_old_images: true
          # Validation settings
          validate_bgp: true
          expected_bgp_neighbors: ["10.0.0.1", "10.0.0.2"]
          validate_vpc: true
          # Network validation
          bgp_convergence_timeout: 300
          ospf_convergence_timeout: 180

    # ============================================================================
    # CISCO IOS-XE DEVICES (Catalyst Switches, ISR/ASR Routers)
    # ============================================================================
    cisco_iosxe:
      hosts:
        # Example IOS-XE Catalyst switch
        iosxe-switch-01:
          ansible_host: 192.168.2.10
          platform: ios
          # Device model (used for firmware filename selection)
          device_model: "C9300"
          target_version: "17.09.04a"

        # Example IOS-XE with install mode settings
        iosxe-router-01:
          ansible_host: 192.168.2.11
          platform: ios
          device_model: "ISR4331"
          target_version: "17.09.04a"
          # Install mode settings (preferred for IOS-XE 17.x+)
          prefer_install_mode: true
          install_mode_timeout: 3600
          # Boot system management
          manage_boot_system: true
          clear_old_boot_entries: true

        # Example IOS-XE with stack settings
        iosxe-stack-01:
          ansible_host: 192.168.2.12
          platform: ios
          device_model: "C9300"
          target_version: "17.09.04a"
          # Stack configuration
          stack_mode: true
          validate_stack_members: true
          stack_master_priority: 15
          # Validation settings
          validate_stack: true
          validate_redundancy: true

    # ============================================================================
    # FORTINET FORTIOS DEVICES (FortiGate Firewalls)
    # ============================================================================
    fortios:
      hosts:
        # Example FortiGate standalone device
        fortigate-01:
          ansible_host: 192.168.3.10
          platform: fortios
          target_firmware: "7.4.1"
          # VDOM settings
          vdom: "root"
          multi_vdom_mode: false

        # Example FortiGate HA cluster member
        fortigate-ha-01:
          ansible_host: 192.168.3.11
          platform: fortios
          target_firmware: "7.4.1"
          # HA cluster settings
          ha_enabled: true
          ha_mode: "active-passive"
          ha_group_id: 1
          ha_priority: 200  # Primary
          check_ha_sync: true
          # HA upgrade coordination
          upgrade_method: "coordinated"
          # Security service validation
          validate_security_services: true
          validate_ipsec_vpn: true
          validate_ssl_vpn: true

        # Example FortiGate with security services
        fortigate-02:
          ansible_host: 192.168.3.12
          platform: fortios
          target_firmware: "7.4.1"
          # Security services validation
          security_services:
            antivirus: true
            ips: true
            web_filter: true
            application_control: true
            email_filter: true
            dlp: true

    # ============================================================================
    # OPENGEAR DEVICES (Console Servers / Smart PDUs)
    # ============================================================================
    opengear:
      hosts:
        # Example modern Opengear console server
        console-server-01:
          ansible_host: 192.168.4.10
          platform: opengear
          device_model: "CM8100"
          device_family: "console_server"
          target_version: "25.07.0"  # Modern YY.MM.x format
          # Console server settings
          notify_active_sessions: true
          maintenance_mode_message: "Console server upgrade - services temporarily unavailable"

        # Example legacy Opengear console server
        console-server-legacy:
          ansible_host: 192.168.4.11
          platform: opengear
          device_model: "CM7100"
          device_family: "console_server"
          target_version: "5.16.4"  # Legacy 5.x.x format
          # Legacy CLI settings
          upgrade_timeout: 1800
          session_message_delay: 60

        # Example Opengear smart PDU
        smart-pdu-01:
          ansible_host: 192.168.4.12
          platform: opengear
          device_family: "smart_pdu"
          target_version: "25.07.0"
          # Smart PDU settings
          critical_outlet_protection: true
          power_safety_threshold: 90

    # ============================================================================
    # METAMAKO MOS DEVICES (Ultra-Low Latency Switches)
    # ============================================================================
    metamako_mos:
      hosts:
        # Example Metamako device
        metamako-01:
          ansible_host: 192.168.5.10
          platform: metamako_mos
          target_firmware: "5.14.0"
          # Ultra-low latency requirements
          max_allowed_latency_ns: 100
          latency_degradation_threshold: 1.1
          enable_latency_monitoring: true
          # Performance validation
          validate_latency_performance: true
          enable_performance_benchmarks: true
          # Timing validation (critical for trading)
          validate_pps_sync: true
          validate_time_accuracy: true
          max_time_drift_ms: 1
          # PTP settings
          ptp_enabled: true
          ptp_domain: 0
          validate_ptp_sync: true

        # Example Metamako with application management
        metamako-02:
          ansible_host: 192.168.5.11
          platform: metamako_mos
          target_firmware: "5.14.0"
          # Application management during upgrade
          manage_applications: true
          applications_to_enable: ["packet_capture", "latency_monitor"]
          applications_to_disable: ["debug_logger"]

  # ==============================================================================
  # LOCALHOST (for testing and development)
  # ==============================================================================
  hosts:
    localhost:
      ansible_connection: local
      ansible_network_os: cisco.nxos.nxos  # Mock value for dry-run testing
      platform: nxos  # Platform identifier for testing

# ==============================================================================
# COMMON PARAMETER EXAMPLES (Can be applied to any host)
# ==============================================================================
#
# The following parameters can be set on any device (host-level overrides):
#
# Authentication (vault-encrypted recommended):
#   ansible_user: "{{ vault_device_username }}"
#   ansible_password: "{{ vault_device_password }}"
#   ansible_ssh_private_key_file: "{{ vault_ssh_key_path }}"
#
# Upgrade Workflow:
#   target_firmware: "firmware-filename.bin"  # Override per-host firmware
#   max_retry_attempts: 3  # Override retry attempts
#   reboot_wait_time: 600  # Override post-reboot wait time (seconds)
#   maintenance_window: true  # Enable maintenance mode for this host
#   auto_rollback: true  # Enable automatic rollback on failure
#
# Validation Settings:
#   skip_validation: false  # Skip network validation
#   network_state_comparison: true  # Compare pre/post upgrade state
#   baseline_capture_enabled: true  # Capture baseline before upgrade
#
# Backup Settings:
#   backup_enabled: true  # Enable config backup
#   rollback_on_failure: true  # Enable rollback on failure
#   keep_backup_count: 3  # Number of backups to retain
#
# Storage Paths:
#   firmware_base_path: "/var/lib/network-upgrade/firmware"
#   backup_base_path: "/var/lib/network-upgrade/backups"
#
# Device Identification:
#   site_name: "datacenter-west"
#   device_role: "access-switch"
#   vendor: "cisco"
#
# Network Validation:
#   ping_test_enabled: true
#   ping_test_host: "8.8.8.8"
#   bgp_enabled: true
#   multicast_enabled: true
#
# Security:
#   hash_verification_enabled: true  # Verify firmware hash
#   signature_validation_enabled: true  # Verify firmware signature
#
# Monitoring:
#   export_metrics: true  # Export metrics to InfluxDB
#   send_notifications: true  # Send notifications
#   notification_on_failure: true
#
# Environmental:
#   check_environmental_sensors: true
#   temperature_threshold_celsius: 45
#   power_threshold_percent: 85
#
# ==============================================================================
# PLATFORM-SPECIFIC PARAMETERS
# ==============================================================================
#
# Complete platform-specific parameters are defined in:
#   - ansible-content/inventory/group_vars/cisco_nxos.yml (121 lines)
#   - ansible-content/inventory/group_vars/cisco_iosxe.yml (158 lines)
#   - ansible-content/inventory/group_vars/fortios.yml (141 lines)
#   - ansible-content/inventory/group_vars/opengear.yml (198 lines)
#   - ansible-content/inventory/group_vars/metamako_mos.yml (122 lines)
#   - ansible-content/inventory/group_vars/all.yml (112 lines - global settings)
#
# Full documentation: docs/inventory-parameters.md
#
# ==============================================================================
