---
# Network Device Upgrade System - Inventory Configuration
#
# This file defines devices for firmware upgrades across multiple vendor platforms.
#
# Documentation: See docs/inventory-parameters.md for complete parameter reference
#               See docs/inventory-parameters.md "Examples" section for detailed host examples
#
# Structure:
#   - All group-level parameters are defined in group_vars/<platform>.yml
#   - Host-specific overrides can be defined inline or in host_vars/<hostname>.yml
#
# Quick Start:
#   1. Add your device under the appropriate platform group
#   2. Set required parameters: ansible_host, platform
#   3. Override platform defaults as needed (optional)
#   4. Refer to group_vars/all.yml for global parameters
#   5. Refer to group_vars/<platform>.yml for platform-specific parameters
#   6. See docs/inventory-parameters.md for comprehensive examples

all:
  # ==============================================================================
  # LOCALHOST (for testing and development)
  # ==============================================================================
  hosts:
    localhost:
      ansible_connection: local
      ansible_network_os: cisco.nxos.nxos  # Mock value for dry-run testing
      platform: nxos  # Platform identifier for testing

  # ==============================================================================
  # PLATFORM GROUPS (for group_vars)
  # ==============================================================================
  # Define empty groups so group_vars files can be loaded without warnings
  children:
    cisco_nxos:
      hosts: {}
    cisco_iosxe:
      hosts: {}
    fortios:
      hosts: {}
    opengear:
      hosts: {}

# ==============================================================================
# PRODUCTION DEVICE CONFIGURATION
# ==============================================================================
#
# Add your production devices below following these patterns:
#
# all:
#   children:
#     cisco_nxos:
#       hosts:
#         switch-01:
#           ansible_host: 192.168.1.10
#           platform: nxos
#
#     cisco_iosxe:
#       hosts:
#         router-01:
#           ansible_host: 192.168.2.10
#           platform: ios
#
#     fortios:
#       hosts:
#         firewall-01:
#           ansible_host: 192.168.3.10
#           platform: fortios
#
#     opengear:
#       hosts:
#         console-01:
#           ansible_host: 192.168.4.10
#           platform: opengear
#
#     
#       hosts:
#         switch-01:
#           ansible_host: 192.168.5.10
#
# ==============================================================================
# DOCUMENTATION
# ==============================================================================
#
# For comprehensive examples and complete parameter documentation, see:
#   docs/inventory-parameters.md
#
# This documentation includes:
#   - Complete parameter reference for all platforms (850+ parameters)
#   - Minimal, common, and advanced configuration examples
#   - Parameter precedence explanation
#   - Best practices and usage guidelines
#
# Platform-specific default parameters are defined in:
#   - ansible-content/inventory/group_vars/cisco_nxos.yml (121 lines)
#   - ansible-content/inventory/group_vars/cisco_iosxe.yml (158 lines)
#   - ansible-content/inventory/group_vars/fortios.yml (141 lines)
#   - ansible-content/inventory/group_vars/opengear.yml (198 lines)
#   - ansible-content/inventory/group_vars/all.yml (112 lines - global settings)
#
# ==============================================================================
