---
# Generic Storage Assessment for Unknown Platforms

- name: Initialize storage_info if not defined
  ansible.builtin.set_fact:
    storage_info: {}
  when: storage_info is not defined

- name: Default storage assessment for unknown platform
  ansible.builtin.set_fact:
    storage_info: >-
      {{ storage_info | combine({
        'total_space_gb': 8,
        'free_space_gb': 4,
        'images_found': ['current-image.bin'],
        'cleanup_candidates': []
      }) }}

- name: Update space check results with storage info
  ansible.builtin.set_fact:
    space_check_results: >-
      {{ space_check_results | combine({
        'available_space': storage_info.free_space_gb,
        'passed': storage_info.free_space_gb >= (required_space_gb | default(2))
      }) }}
