name: 'Integration Tests'
description: 'Run integration tests and check mode validation'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13.6'

runs:
  using: 'composite'
  steps:
    - name: Setup Ansible Environment
      uses: ./.github/actions/setup-ansible
      with:
        python-version: ${{ inputs.python-version }}
        cache-key-suffix: 'integration-tests'

    - name: Run check mode tests
      shell: bash
      run: |
        ANSIBLE_ROLES_PATH=ansible-content/roles \
        ANSIBLE_CONFIG=ansible-content/ansible.cfg \
        ansible-playbook -i tests/mock-inventories/all-platforms.yml \
          --check --diff tests/integration-tests/check-mode-tests.yml

    - name: Test workflow integration validation
      shell: bash
      run: |
        ANSIBLE_ROLES_PATH=ansible-content/roles \
        ANSIBLE_CONFIG=ansible-content/ansible.cfg \
        ansible-playbook tests/integration-tests/workflow-tests.yml \
          --limit localhost