---
name: Ansible Tests Simple

on:
  workflow_dispatch:
    inputs:
      test_level:
        description: 'Test level'
        required: false
        default: 'standard'
        type: choice
        options:
          - 'standard'
          - 'comprehensive'

permissions:
  contents: read

jobs:
  lint-and-syntax:
    name: Lint and Syntax Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade ansible
          pip install yamllint ansible-lint

      - name: Install Ansible collections
        run: |
          ansible-galaxy collection install \
            -r ansible-content/collections/requirements.yml \
            --force

      - name: Run basic tests
        run: |
          echo "✅ Running basic lint tests..."
          yamllint --version
          ansible-lint --version
          ansible --version
          echo "✅ Basic tests completed"