---
name: Ansible Tests - Main Workflow

# Cancel in-progress runs when a new workflow is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    # Run comprehensive tests weekly on Sundays at 3:00 AM UTC
    - cron: '0 3 * * 0'
  workflow_dispatch:
    inputs:
      test_level:
        description: 'Test level to run'
        required: false
        default: 'standard'
        type: choice
        options:
        - 'standard'
        - 'comprehensive'
        - 'critical-gaps-only'

permissions:
  contents: write
  issues: read
  checks: read
  pull-requests: read
  packages: write

jobs:
  # Standard tests that run on all pushes and PRs
  call-lint-and-syntax:
    name: Call Lint and Syntax Tests
    uses: ./.github/workflows/lint-and-syntax.yml

  call-unit-tests:
    name: Call Unit Tests
    uses: ./.github/workflows/unit-tests.yml

  call-integration-tests:
    name: Call Integration Tests
    uses: ./.github/workflows/integration-tests.yml

  call-security-scan:
    name: Call Security Scan
    uses: ./.github/workflows/security-scan.yml

  call-mock-device-tests:
    name: Call Mock Device Framework Tests
    uses: ./.github/workflows/mock-device-tests.yml

  # Conditional tests that run based on event type and input
  call-molecule-tests:
    name: Call Molecule Tests
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'pull_request' && github.base_ref == 'main') || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    uses: ./.github/workflows/molecule-tests.yml

  call-comprehensive-tests:
    name: Call Comprehensive Test Suites
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && (inputs.test_level == 'comprehensive' || inputs.test_level == 'critical-gaps-only'))
    uses: ./.github/workflows/comprehensive-tests.yml
    with:
      test_level: ${{ inputs.test_level || 'comprehensive' }}

  # Container build only runs after all standard tests pass
  call-container-build:
    name: Build Container Image
    needs: [call-lint-and-syntax, call-unit-tests, call-integration-tests, call-security-scan, call-mock-device-tests]
    # Also include conditional dependencies if they ran
    if: |
      github.event_name == 'push' && github.ref == 'refs/heads/main' &&
      (always() && !failure() && !cancelled())
    uses: ./.github/workflows/build-container.yml
    with:
      push_image: true
      platforms: 'linux/amd64,linux/arm64'
    secrets: inherit