---
name: Lint and Syntax Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

permissions:
  contents: read
  checks: read

jobs:
  lint-and-syntax:
    name: Lint and Syntax Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13.7"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ansible Environment
        uses: ./.github/actions/setup-ansible
        with:
          python-version: ${{ matrix.python-version }}
          cache-key-suffix: 'lint-syntax'

      - name: Run YAML syntax validation
        run: |
          python3 tests/validation-scripts/yaml-validator.py --ansible-only

      - name: Run yamllint
        run: |
          yamllint ansible-content/
        continue-on-error: true

      - name: Run ansible-lint
        run: |
          ansible-lint ansible-content/playbooks/ ansible-content/roles/
        continue-on-error: true

      - name: Test playbook syntax
        run: |
          ansible-playbook --syntax-check \
            ansible-content/playbooks/main-upgrade-workflow.yml