---
name: Molecule Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 0'

permissions:
  contents: read

jobs:
  molecule-tests:
    name: Molecule Tests
    runs-on: ubuntu-latest
    # Run molecule tests only for main branch pushes, PRs to main, or manual triggers
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'pull_request' && github.base_ref == 'main') || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.7'

      - name: Install dependencies
        run: |
          pip install --upgrade ansible molecule molecule-plugins[docker] docker
          # Clear any existing collections to avoid conflicts
          rm -rf ~/.ansible/collections
          # Install collections to user directory
          ansible-galaxy collection install \
            -r ansible-content/collections/requirements.yml \
            --force --ignore-certs --collections-path ~/.ansible/collections

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run molecule tests for network upgrade
        run: |
          cd tests/molecule-tests
          molecule test -s network-upgrade-test
        env:
          MOLECULE_NO_LOG: false
          MOLECULE_VERBOSITY: 1

      - name: Run default molecule tests
        run: |
          cd tests/molecule-tests
          molecule test -s default
        env:
          MOLECULE_NO_LOG: false